global:
  marketplace-ami: false
  owner: srrampra@amazon.com
  qsname: connect-integration-test
  regions:
  - us-east-1
  reporting: true
tests:
  scenario1:
    parameter_input: defaults.json
    template_file: test.template
    regions:
    - us-east-1

