global:
  marketplace-ami: false
  owner: ramprasad1@gmail.com
  qsname: connect-integration-test
  regions:
  - us-east-1
  reporting: true
tests:
  defaults:
    parameter_input: defaults.json
    template_file: test.template
